### ISSUE TITLE
Can't download 

### ISSUE THREAD

**Issue by Wralui** [DasKraken/CR-dl#16]
Serie like [cromartie-high-school](https://www.crunchyroll.com/cromartie-high-school)
Code error 
`CR-DL>cr-dl download https://www.crunchyroll.com/cromartie-high-school/episode-1-i-used-to-be-a-bad-boy-bragging-contest-739313 480p
(Flash Player)
Subtitles for  not available. Skipping...
No subtitles will be included.
[]
RuntimeException: No resolutions found.
    at getMaxWantedResolution (C:\Users\ADMIN\AppData\Roaming\npm\node_modules\cr-dl\src\CrDl.js:198:11)
    at Object.downloadVideoUrl (C:\Users\ADMIN\AppData\Roaming\npm\node_modules\cr-dl\src\CrDl.js:479:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
`
and if I try to download the entire season 
`cr-dl download https://www.crunchyroll.com/en-gb/cromartie-high-school --season 2
Error: No Episodes found.`

**Comment by Wralui** [comment]
Forget about it, I had to switch region and vpn, restricted anime...
