### ISSUE TITLE
Unable to download certain anime

### ISSUE THREAD

**Issue by lindraden** [DasKraken/CR-dl#23]
Hi,

I had a quick search of the issues that were open and resolved but couldn't see anything there. 
Some of the Crunchyroll links work fine (Haikyuu) while others don't (Yu-Gi-Oh! 5'Ds)

I am running this command `cr-dl download -c 5 -l enUS https://www.crunchyroll.com/yu-gi-oh-5ds --seasons 3,4`
and getting the following error
```downloading [████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 21% | 132 MB/635 MB | Speed: 8.26 MB/s | ETA:7
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'tmp/VodVidData/seg-32-v1-a1.ts'
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at WriteStream.onerror (_stream_readable.js:737:7)
    at WriteStream.emit (events.js:200:13)
    at internal/fs/streams.js:289:12
    at FSReqCallback.oncomplete (fs.js:153:23) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'tmp/VodVidData/seg-32-v1-a1.ts'
}```

Not sure what the error is as I don't know nodejs

**Comment by lindraden** [comment]
Looks like just a Blip. Seems to be working fine now..
