### ISSUE TITLE
Can't "mux" on Ubuntu

### ISSUE THREAD

**Issue by valascus** [DasKraken/CR-dl#5]
Getting this error when it's time to mux the file:

`RuntimeException: ffmpeg process exited with code 1
    at ChildProcess.proc.on (/usr/lib/node_modules/cr-dl/src/processVideo.js:82:24)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
`

ffmpeg is at version 4.1, as in my windows pc and node is at 10.

**Comment by valascus** [comment]
It doesn't even create the file VodVid.m3u8, which could be the reason.
