### ISSUE TITLE
Network error: HTTP status code: 502.

### ISSUE THREAD

**Issue by theruleof4** [DasKraken/CR-dl#53]
With some series this error is showing:

I tried with this link: https://www.crunchyroll.com/rezero-starting-life-in-another-world-

NetworkException: HTTP status code: 502
    at Request.<anonymous> (/media/sdc1/theruleof4/lib/node_modules/cr-dl/src/ListDownloader.js:92:36)
    at Request.emit (events.js:203:13)
    at Request.onRequestResponse (/media/sdc1/theruleof4/lib/node_modules/cr-dl/node_modules/request/request.js:1059:10)
    at ClientRequest.emit (events.js:208:15)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:575:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
    at TLSSocket.socketOnData (_http_client.js:449:22)
    at TLSSocket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
events.js:180
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'tmp_hluucb/VodVidData/seg-124-v1-a1.ts'
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at WriteStream.onerror (_stream_readable.js:744:7)
    at WriteStream.emit (events.js:203:13)
    at internal/fs/streams.js:289:12
    at FSReqCallback.oncomplete (fs.js:153:23) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'tmp_hluucb/VodVidData/seg-124-v1-a1.ts'

**Comment by DasKraken** [comment]
Can you try again? I assume that they just had some server problems.
