### ISSUE TITLE
 RuntimeException: ffmpeg process exited with code 1

### ISSUE THREAD

**Issue by luannbr** [DasKraken/CR-dl#54]
Downloading to "A Certain Scientific Railgun T [1080p]/A Certain Scientific Railgun T - 13 - System - Aquela que obtém o poder dos deuses enquanto ainda possui corpo mortal [1080p].mkv"...
downloading [████████████████████████████████████████] 100% | 1.48 GB/1.48 GB |
muxing [░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 0% | {curDuration}/{totalDura
RuntimeException: ffmpeg process exited with code 1
    at ChildProcess.proc.on (/usr/lib/node_modules/cr-dl/src/processVideo.js:99:24)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)

//

 ffmpeg --version
ffmpeg version 2.8.8 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-39)
  configuration: --disable-static --enable-gpl --enable-version3 --enable-nonfree --enable-shared --enable-libmp3lame --enable-libx264 --enable-libvpx --enable-libvorbis --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopencore-amrnb --enable-libtheora --enable-libxvid --enable-libfdk_aac --enable-libopus --enable-libfreetype --enable-libfaac
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101

how solve this?

**Comment by DasKraken** [comment]
Please try again using CR-dl version 4.0.0. This will give out the output from ffmpeg on error. I'm not sure, but it could possibly be because of an old ffmpeg version.

**Comment by MonoConBigotes** [comment]
It seems to me, that it is due to the maximum supported size of the name (characters, number of chars in the title)...
