### ISSUE TITLE
name: 'CaptchaError',   message: 'captcha'

### ISSUE THREAD

**Issue by caunio** [DasKraken/CR-dl#58]
when I try to download any series / subtitles, I get this error. I tried with cookies from cr-dl and cookies from the browser - no change.
```
CaptchaError: captcha
    at validateResponse (C:\Users\caunio\AppData\Roaming\npm\node_modules\@derkraken\cr-dl\node_modules\cloudscraper\index.js:273:11)
    at onCloudflareResponse (C:\Users\caunio\AppData\Roaming\npm\node_modules\@derkraken\cr-dl\node_modules\cloudscraper\index.js:222:5)
    at onRequestResponse (C:\Users\caunio\AppData\Roaming\npm\node_modules\@derkraken\cr-dl\node_modules\cloudscraper\index.js:205:5)
    at Request.<anonymous> (C:\Users\caunio\AppData\Roaming\npm\node_modules\@derkraken\cr-dl\node_modules\cloudscraper\index.js:149:7)
    at Object.onceWrapper (events.js:418:26)
    at Request.emit (events.js:311:20)
    at Request.<anonymous> (C:\Users\caunio\AppData\Roaming\npm\node_modules\@derkraken\cr-dl\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:311:20)
    at Gunzip.<anonymous> (C:\Users\caunio\AppData\Roaming\npm\node_modules\@derkraken\cr-dl\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:417:28)
    at Gunzip.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  name: 'CaptchaError',
  message: 'captcha'
}
```

**Comment by Kanekid2m** [comment]
ran into the same issue today. Hope DasKraken can fix it soon

**Comment by Abu3safeer** [comment]
Just open it in browser and solve the captcha, then export the cookies.txt to script directory.

it is explained here:
https://github.com/DasKraken/CR-dl#alternative-login-methods-to-cr-dl

**Comment by Kanekid2m** [comment]
> 
> 
> Just open it in browser and solve the captcha, then export the cookies.txt to script directory.
> 
> it is explained here:
> https://github.com/DasKraken/CR-dl#alternative-login-methods-to-cr-dl

Same result. I keep getting the same error.

**Comment by Abu3safeer** [comment]
Looks like it is an issue with "cloudscraper"

**Comment by besweeet** [comment]
Also unable to sign in due to the same captcha error. Tried cookies.txt using the Chrome extension and the same captcha error displays. youtube-dl it is.

**Comment by DasKraken** [comment]
I hope it works again with latest version

**Comment by Abu3safeer** [comment]
Yes it works, even login works.

**Comment by besweeet** [comment]
> I hope it works again with latest version

Why did you close this? It still doesn't work with 4.0.1.

**Comment by Abu3safeer** [comment]
> Why did you close this? It still doesn't work with 4.0.1.

It works, just copy cookies file from browser if you cannot login with cr-dl cli method.

**Comment by besweeet** [comment]
> It works, just copy cookies file from browser if you cannot login with cr-dl cli method.

I did that but the captcha error still displays. cookies.txt is placed in the same directory as cr-dl, so the --cookies flag isn't needed.

**Comment by Abu3safeer** [comment]
Looks like it does not work with proxy, I tried using a proxy and got the same message

**Comment by Abu3safeer** [comment]
Hello @DasKraken 
This issue still present if with --proxy, can you check that?
