### ISSUE TITLE
Cloudscrapper VPN issue

### ISSUE THREAD

**Issue by ark626** [DasKraken/CR-dl#65]
If a VPN is used there is an issue with Cloudscrapper.

Seems like a captcha is there and is preventing us from get further.
Also if i use the cookies.txt which i generated from firefox it doesnt work because it leads to the same behavior.

>C:\CR DL>cr-dl download https://www.crunchyroll.com/squid-girl --cookies "C:\Users\ark-6\AnimeLoader\anime-dl-master\anime_dl\CR DL\cookies.txt"
>CaptchaError: captcha
>    at validateResponse (C:\snapshot\CR-dl\node_modules\cloudscraper\index.js:273:11)
>    at onCloudflareResponse (C:\snapshot\CR-dl\node_modules\cloudscraper\index.js:222:5)
>    at onRequestResponse (C:\snapshot\CR-dl\node_modules\cloudscraper\index.js:205:5)
>    at Request.<anonymous> (C:\snapshot\CR-dl\node_modules\cloudscraper\index.js:149:7)
>    at Object.onceWrapper (events.js:418:26)
>    at Request.emit (events.js:311:20)
>    at Request.<anonymous> (C:\snapshot\CR-dl\node_modules\request\request.js:1154:10)
>    at Request.emit (events.js:311:20)
>    at Gunzip.<anonymous> (C:\snapshot\CR-dl\node_modules\request\request.js:1076:12)
>    at Object.onceWrapper (events.js:417:28)
>    at Gunzip.emit (events.js:323:22)
>    at endReadableNT (_stream_readable.js:1204:12)
>    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
>  name: 'CaptchaError',
>  message: 'captcha'
> }

**Comment by orezraey** [comment]
Same

**Comment by LuisLucas32** [comment]
Also having this problem but im not on a vpn :/

**Comment by grFKkx4HNa42bYUgZdk** [comment]
I have the same error...

![cr](https://user-images.githubusercontent.com/67099667/85006644-0047d980-b120-11ea-9e94-f470fdbbc31f.PNG)

**Comment by Kyouma95** [comment]
Same error without using vpn, but only if i try to download entire series. When downloading with the Episode URL it works.

**Comment by LuisLucas32** [comment]
> Same error without using vpn, but only if i try to download entire series. When downloading with the Episode URL it works.

I just tried downloading using the episode url and it works. Thanks for the quick fix. Just a shame I can't download multiple episodes at once.
