### ISSUE TITLE
always returns captcha (v4.0.1)

### ISSUE THREAD

**Issue by ronaldgameking** [DasKraken/CR-dl#71]
Also with exported cookie.txt
```
CaptchaError: captcha
    at validateResponse (C:\snapshot\CR-dl\node_modules\cloudscraper\index.js:273:11)
    at onCloudflareResponse (C:\snapshot\CR-dl\node_modules\cloudscraper\index.js:222:5)
    at onRequestResponse (C:\snapshot\CR-dl\node_modules\cloudscraper\index.js:205:5)
    at Request.<anonymous> (C:\snapshot\CR-dl\node_modules\cloudscraper\index.js:149:7)
    at Object.onceWrapper (events.js:418:26)
    at Request.emit (events.js:311:20)
    at Request.<anonymous> (C:\snapshot\CR-dl\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:311:20)
    at Gunzip.<anonymous> (C:\snapshot\CR-dl\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:417:28)
    at Gunzip.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  name: 'CaptchaError',
  message: 'captcha'
}
```

**Comment by MonoConBigotes** [comment]
the only way is put the url of one each episode...

**Comment by RobertusIT** [comment]
> l'unico modo è mettere l'url di uno ogni episodio ...

doesn't works also in this way

**Comment by darkairo** [comment]
The problem is that trying to login the account also returns a conflict with cloudflare

**Comment by RobertusIT** [comment]
> The problem is that trying to login the account also returns a conflict with cloudflare

this app doesn't works if isn't update

use crounchyroll downloader at the moment

**Comment by MonoConBigotes** [comment]
> 
> 
> The problem is that trying to login the account also returns a conflict with cloudflare

usea a coockie exporter plugin in chrome or firefox...

**Comment by passthesh3ll** [comment]
> > l'unico modo è mettere l'url di uno ogni episodio ...

> doesn't works also in this way

if you put one episode download command, you can download without problems. Don't use a bash file if you don't write a file like this (because you need to close the current _cmd_ session in order to kill cr-dl and avoid that it manages more than one link):
**example_download.bat**
```
if downloaded_file not exists: cr-dl download command (1 episode url)
example_download.bat
exit
if downloaded_file not exists: cr-dl download command (1 eposode url)
example_download.bat
exit
..
```
real working example (first line is a command to delete all temporary folders of cr-dl, assuming the bat file is in the same cr-dl directory):
**example_download.bat**
```
for /d %%a in (".\*") do rd "%%a" /q /s
if not exist "/path/episode1.mkv" ( <cr-dl download episode 1> & start example_download.bat & exit ) 
if not exist "/path/episode2.mkv" ( <cr-dl download episode 2> & start example_download.bat & exit ) 
...
```
the captcha (or stopped download) problems occurs when cr-dl manages more than one link in download or fetching. If you do a bat file using a sequence like this, you can sequentially download without problems. Same cloudflare problems occur with login process, you have to use cookies to avoid it.

**Comment by fidodone** [comment]
> > > l'unico modo è mettere l'url di uno ogni episodio ...
> 
> > doesn't works also in this way
> 
> if you put one episode download command, you can download without problems. Don't use a bash file if you don't write a file like this (because you need to close the current _cmd_ session in order to kill cr-dl and avoid that it manages more than one link):
> **example_download.bat**
> 
> ```
> if downloaded_file not exists: cr-dl download command (1 episode url)
> example_download.bat
> exit
> if downloaded_file not exists: cr-dl download command (1 eposode url)
> example_download.bat
> exit
> ..
> ```
> 
> real working example (first line is a command to delete all temporary folders of cr-dl, assuming the bat file is in the same cr-dl directory):
> **example_download.bat**
> 
> ```
> for /d %%a in (".\*") do rd "%%a" /q /s
> if not exist "/path/episode1.mkv" ( <cr-dl download episode 1> & start example_download.bat & exit ) 
> if not exist "/path/episode2.mkv" ( <cr-dl download episode 2> & start example_download.bat & exit ) 
> ...
> ```
> 
> the captcha (or stopped download) problems occurs when cr-dl manages more than one link in download or fetching. If you do a bat file using a sequence like this, you can sequentially download without problems. Same cloudflare problems occur with login process, you have to use cookies to avoid it.

Do you have any linux script?

**Comment by RobertusIT** [comment]
> > > l'unico modo è mettere l'url di uno ogni episodio ...
> 
> > doesn't works also in this way
> 
> if you put one episode download command, you can download without problems. Don't use a bash file if you don't write a file like this (because you need to close the current _cmd_ session in order to kill cr-dl and avoid that it manages more than one link):
> **example_download.bat**
> 
> ```
> if downloaded_file not exists: cr-dl download command (1 episode url)
> example_download.bat
> exit
> if downloaded_file not exists: cr-dl download command (1 eposode url)
> example_download.bat
> exit
> ..
> ```
> 
> real working example (first line is a command to delete all temporary folders of cr-dl, assuming the bat file is in the same cr-dl directory):
> **example_download.bat**
> 
> ```
> for /d %%a in (".\*") do rd "%%a" /q /s
> if not exist "/path/episode1.mkv" ( <cr-dl download episode 1> & start example_download.bat & exit ) 
> if not exist "/path/episode2.mkv" ( <cr-dl download episode 2> & start example_download.bat & exit ) 
> ...
> ```
> 
> the captcha (or stopped download) problems occurs when cr-dl manages more than one link in download or fetching. If you do a bat file using a sequence like this, you can sequentially download without problems. Same cloudflare problems occur with login process, you have to use cookies to avoid it.

i didn't understand how to

please can you provide to an example with links?
