### ISSUE TITLE
got.paginate = async function* (url, options) { ^

### ISSUE THREAD

**Issue by xgrons** [DasKraken/CR-dl#76]
/tools/node/lib/node_modules/@derkraken/cr-dl/node_modules/got/dist/source/create.js:101
    got.paginate = async function* (url, options) {
                                 ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tools/node/lib/node_modules/@derkraken/cr-dl/node_modules/got/dist/source/index.js:7:18)

**Comment by MonoConBigotes** [comment]
Try this fork
https://github.com/n0x073/CR-dl

**Comment by xgrons** [comment]
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/tools/node/lib/node_modules/@n0x073/cr-dl/node_modules/node-libcurl/lib/binding' 
gyp WARN EACCES user "undefined" does not have permission to access the dev dir "/root/.node-gyp/8.11.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/tools/node/lib/node_modules/@n0x073/cr-dl/node_modules/node-libcurl/.node-gyp"
gyp WARN EACCES user "undefined" does not have permission to access the dev dir "/tools/node/lib/node_modules/@n0x073/cr-dl/node_modules/node-lib

**Comment by xVoldx** [comment]
when i run npm install -g @n0x073/cr-dl
i get this error

**Comment by xgrons** [comment]
> Try this fork
> https://github.com/n0x073/CR-dl

when i run npm install -g @n0x073/cr-dl
i get this error
