### ISSUE TITLE
can not log in. need help

### ISSUE THREAD

**Issue by post-master** [DasKraken/CR-dl#77]
**can not log in. here is the full log file:**

`C:\Users\Minhajul Islam\Downloads\cr-dl>]cd-dl login [options] [jak528@gmail.com] [rushhour2]
']cd-dl' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Minhajul Islam\Downloads\cr-dl>cd-dl login [options] [jak528@gmail.com] [rushhour2]
'cd-dl' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Minhajul Islam\Downloads\cr-dl>

C:\Users\Minhajul Islam\Downloads\cr-dl>cr-dl login [options] [ja***@gmail.com] [*****ur2]
CaptchaError: captcha
    at validateResponse (C:\snapshot\CR-dl\node_modules\cloudscraper\index.js:273:11)
    at onCloudflareResponse (C:\snapshot\CR-dl\node_modules\cloudscraper\index.js:222:5)
    at onRequestResponse (C:\snapshot\CR-dl\node_modules\cloudscraper\index.js:205:5)
    at Request.<anonymous> (C:\snapshot\CR-dl\node_modules\cloudscraper\index.js:149:7)
    at Object.onceWrapper (events.js:418:26)
    at Request.emit (events.js:311:20)
    at Request.<anonymous> (C:\snapshot\CR-dl\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:311:20)
    at Gunzip.<anonymous> (C:\snapshot\CR-dl\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:417:28)
    at Gunzip.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  name: 'CaptchaError',
  message: 'captcha'
}

C:\Users\Minhajul Islam\Downloads\cr-dl>`

**when I try to use cookies. I got this error:**

`C:\Users\Minhajul Islam\Downloads\cr-dl>cr-dl --cookies cookie.txt
error: unknown option '--cookies'

C:\Users\Minhajul Islam\Downloads\cr-dl>`

**Comment by GatoSoft-Software** [comment]
I'm having mostly the same problem.
 Anyway, @MinhajBoss, you're using the `--cookies` parameter in the wrong way. You should use "login" before, like this:
`cr-dl login --cookies cookies.txt`
 However, even with that, I had no luck with it. I'm still getting the "CaptchaError" despite I've used correctly the "cookies.txt" extension on Firefox and even using the absolute path to the file.
What am I doing wrong? 🤷‍♂️
